detectors:
  Attribute:
    enabled: true
    exclude: []
  BooleanParameter:
    enabled: true
    exclude: []
  ClassVariable:
    enabled: true
    exclude: []
  ControlParameter:
    enabled: true
    exclude: []
  DataClump:
    enabled: true
    exclude: []
    max_copies: 2
    min_clump_size: 2
  DuplicateMethodCall:
    enabled: true
    exclude: []
    max_calls: 1
    allow_calls:
      - 'Rails.env'
  FeatureEnvy:
    enabled: true
    exclude:
      - WithStatsScopes#this_month
  InstanceVariableAssumption:
    enabled: false
    exclude: []
  IrresponsibleModule:
    enabled: false
    exclude: []
  LongParameterList:
    enabled: true
    exclude: []
    max_params: 3
    overrides:
      initialize:
        max_params: 5
  LongYieldList:
    enabled: true
    exclude: []
    max_params: 3
  ManualDispatch:
    enabled: true
    exclude: []
  MissingSafeMethod:
    enabled: false
    exclude: []
  ModuleInitialize:
    enabled: true
    exclude: []
  NestedIterators:
    enabled: true
    exclude: []
    max_allowed_nesting: 1
    ignore_iterators:
      - tap
  NilCheck:
    enabled: false
    exclude: []
  RepeatedConditional:
    enabled: true
    exclude: []
    max_ifs: 2
  SubclassedFromCoreClass:
    enabled: true
    exclude: []
  TooManyConstants:
    enabled: true
    exclude: []
    max_constants: 5
  TooManyInstanceVariables:
    enabled: true
    exclude: []
    max_instance_variables: 4
  TooManyMethods:
    enabled: true
    exclude: []
    max_methods: 15
  TooManyStatements:
    enabled: true
    exclude:
      - initialize
    max_statements: 9
  UncommunicativeMethodName:
    enabled: true
    exclude: []
    reject:
      - "/^[a-z]$/"
      - "/[0-9]$/"
      - "/[A-Z]/"
    accept: []
  UncommunicativeModuleName:
    enabled: true
    exclude: []
    reject:
      - "/^.$/"
      - "/[0-9]$/"
    accept:
      - "/V[0-9]/"
  UncommunicativeParameterName:
    enabled: true
    exclude: []
    reject:
      - "/^.$/"
      - "/[0-9]$/"
      - "/[A-Z]/"
      - "/^_/"
    accept: []
  UncommunicativeVariableName:
    enabled: true
    exclude: [e]
    reject:
      - "/^.$/"
      - "/[0-9]$/"
      - "/[A-Z]/"
    accept:
      - "/^_$/"
  UnusedParameters:
    enabled: true
    exclude: []
  UnusedPrivateMethod:
    enabled: false
    exclude: []
  UtilityFunction:
    enabled: true
    exclude:
      - Devise::TokenGenerator
    public_methods_only: false

directories:
  "app/services":
    UtilityFunction:
      enabled: false
    FeatureEnvy:
      enabled: false
  "app/presenters":
    UtilityFunction:
      enabled: false
    FeatureEnvy:
      enabled: false
  "app/jobs":
    UtilityFunction:
      enabled: false
    FeatureEnvy:
      enabled: false
  "app/uploaders":
    UtilityFunction:
      enabled: false
  "spec/support":
    UtilityFunction:
      enabled: false
  "app/validators":
    ControlParameter:
      enabled: false
  "db/migrate":
    UtilityFunction:
      enabled: false
    FeatureEnvy:
      enabled: false
    TooManyStatements:
      enabled: false
  "spec/mailers/previews":
    UtilityFunction:
      enabled: false
  "rubocop":
    UtilityFunction:
      enabled: false
    FeatureEnvy:
      enabled: false
  "app/admin":
    FeatureEnvy:
      enabled: false
