default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  timeout: 5000
  username:
  password:

development:
  <<: *default
  database: rails_api_boilerplate_development

test:
  <<: *default
  database: rails_api_boilerplate_test
